# Generated by Django 2.2.1 on 2020-11-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190511_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='pincode',
        ),
    ]
